<div class="newEntry">
    <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
        User: <?php echo $this->newEntryVars["usr"];?><br>
        <textarea name="shitpost" rows="8" cols="80"></textarea><br>
        <span class="error"> <?php echo $this->newEntryVars["shtErr"];?></span><br>
        <input type="submit" name="submit" value="SHITPOST!"><br><br>
    </form>
</div>