<div class="login">
    <h3>Please login to shitpost.</h3>
    <br><br>
    <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
        User: <input type="text" name="usr" value="<?php echo $usr;?>"><br>

        Password: <input type="password" name="pwd"><br>
        <span class="error"> <?php echo $loginErr;?></span><br><br>

        <input class="submit" type="submit" name="submit" value="Enter">
    </form>
</div>