<div class="newEntry">
    <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]);?>">
        <div class="userBar">
            User: <?php echo $this->newEntryVars["usr"];?>
            <button class="logout" name="logout" value="true">LOGOUT</button>
        </div>
        <div class="shitpostForm">
            <textarea name="shitpost" rows="8" cols="80"></textarea><br>
            <span class="error"> <?php echo $this->newEntryVars["shtErr"];?></span>
        </div>
        <button class="submit" name="submit">SHITPOST!</button>
    </form>
</div>